
import { GoogleGenAI, Type } from "@google/genai";
import { STYLE_PROMPT_SUFFIX } from "../constants";
import type { Article } from "../types";

let ai: GoogleGenAI | null = null;

const getAI = () => {
  if (!ai) {
    if (!process.env.API_KEY) {
      throw new Error("API_KEY environment variable not set");
    }
    ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  }
  return ai;
};

const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(file);
        reader.onload = () => {
            const result = reader.result as string;
            // result is 'data:mime/type;base64,the_base64_string'
            // we need to remove the prefix
            const base64String = result.split(',')[1];
            resolve(base64String);
        };
        reader.onerror = error => reject(error);
    });
};

export const extractTextFromFile = async (file: File): Promise<string> => {
    try {
        const genAI = getAI();
        const base64Data = await fileToBase64(file);

        const response = await genAI.models.generateContent({
            model: 'gemini-3-pro-preview',
            contents: [
                { text: "Extract the text content from this document. Preserve formatting like paragraphs by using newline characters." },
                {
                    inlineData: {
                        mimeType: file.type,
                        data: base64Data,
                    }
                }
            ]
        });

        return response.text ?? '';
    } catch (error) {
        console.error("Error extracting text from file:", error);
        if (error instanceof Error) {
            throw new Error(`Gemini API Error: ${error.message}`);
        }
        throw new Error("An unknown error occurred during text extraction.");
    }
};

export const generateMagazineImage = async (prompt: string): Promise<string> => {
  try {
    const genAI = getAI();
    const fullPrompt = `${prompt}, ${STYLE_PROMPT_SUFFIX}`;
    
    const response = await genAI.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: fullPrompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: '3:4', // A4 paper aspect ratio is roughly 1:1.414, 3:4 is close
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64String = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64String}`;
    } else {
      throw new Error("No image was generated by the API.");
    }
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    if (error instanceof Error) {
        throw new Error(`Gemini API Error: ${error.message}`);
    }
    throw new Error("An unknown error occurred during image generation.");
  }
};

export const generateArticleFromSource = async (sourceContent: string): Promise<Pick<Article, 'headline' | 'author' | 'body'>> => {
  try {
    const genAI = getAI();
    
    const prompt = `You are an expert magazine editor. Based on the following source content, write a compelling magazine article. The article should have a catchy headline, a byline for the author (if not available, use 'Staff Writer'), and a well-structured body of around 200-300 words. The tone should be engaging and professional.

Source Content:
---
${sourceContent}
---

Return the article in the specified JSON format.`;

    const response = await genAI.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            headline: { type: Type.STRING, description: "The catchy headline of the article." },
            author: { type: Type.STRING, description: "The author of the article. Use 'Staff Writer' if unknown." },
            body: { type: Type.STRING, description: "The main body content of the article, approximately 200-300 words." },
          },
          required: ['headline', 'author', 'body'],
        },
      },
    });

    const jsonText = response.text.trim();
    const generatedArticle = JSON.parse(jsonText);
    
    if (typeof generatedArticle.headline !== 'string' || typeof generatedArticle.author !== 'string' || typeof generatedArticle.body !== 'string') {
        throw new Error("Generated article has an invalid format.");
    }
    
    return generatedArticle;

  } catch (error) {
    console.error("Error generating article from source:", error);
    if (error instanceof Error) {
        throw new Error(`Gemini API Error: ${error.message}`);
    }
    throw new Error("An unknown error occurred during article generation.");
  }
};
